// src/lib/habitExport.js
import { HABITS, HABIT_CATEGORIES } from './habits';
import { formatDateDisplay, calculatePercentage } from './habitUtils';

export function generateTextReport(dayData, userName, tomorrowTargets = []) {
  if (!dayData) return '';

  const date       = formatDateDisplay(dayData.date);
  const score      = dayData.score;
  const total      = dayData.totalHabits || HABITS.length;
  const percentage = calculatePercentage(score, total);

  let report = `══════════════════════════════\n`;
  report    += `  BRIGHTEN — Daily Report\n`;
  report    += `══════════════════════════════\n\n`;
  report    += `📅 ${date}\n`;
  report    += `👤 ${userName}\n`;
  report    += `📊 Score: ${score}/${total} (${percentage}%)\n\n`;

  const todayTargets = dayData.targets || [];
  if (todayTargets.length > 0) {
    const done = todayTargets.filter(t => t.done).length;
    report += `── 🎯 Today's Targets (${done}/${todayTargets.length}) ──\n`;
    todayTargets.forEach(t => { report += `  ${t.done ? '✅' : '❌'} ${t.text}\n`; });
    report += '\n';
  }

  HABIT_CATEGORIES.forEach(category => {
    report += `── ${category.icon} ${category.name} ──\n`;
    HABITS.filter(h => h.category === category.id).forEach(habit => {
      const data   = dayData.habits?.[habit.id];
      const status = data?.done ? '✅' : '❌';
      const time   = data?.timestamp
        ? new Date(data.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
        : '';

      report += `  ${status} ${habit.name}`;
      if (time) report += ` (${time})`;
      report += '\n';

      if (data?.details && habit.detailField) {
        const val = data.details[habit.detailField.key];
        if (val) {
          if (habit.detailField.type === 'tags' && typeof val === 'string' && val.includes('||')) {
            val.split('||').filter(t => t.trim()).forEach(tag => { report += `     • ${tag}\n`; });
          } else {
            report += `     → ${val}\n`;
          }
        }
      }
    });
    report += '\n';
  });

  if (tomorrowTargets.length > 0) {
    report += `── 📋 Tomorrow's Targets ──\n`;
    tomorrowTargets.forEach(t => { report += `  • ${t.text}\n`; });
    report += '\n';
  }

  const now = new Date();
  const exportTime = now.toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true,
  });

  report += `\n══════════════════════════════\n`;
  report += `  Generated by Focus Tracker ✨\n`;
  report += `  Exported: ${exportTime}\n`;
  report += `══════════════════════════════`;

  return report;
}
